### ISSUE TITLE
Where is the Analyze package?

### ISSUE THREAD

**Issue by TechAkayy** [vuedx/preview#30]
Hi there,

I'm test-riding Preview, it's amazing, thanks for this. 

I'm also after the Analyze package, Rahul mentioned it here ([youtu.be/dh7Mj0cCVjY?list=PLMapeSQlw8ybn7CqkqsII7f_HwKN-k-SM&t=1030](https://youtu.be/dh7Mj0cCVjY?list=PLMapeSQlw8ybn7CqkqsII7f_HwKN-k-SM&t=1030)). 

I couldn't find it anymore in https://github.com/vuedx/languagetools repo. I notice that it's used in this Preview repo - https://github.com/vuedx/preview/blob/main/packages/preview/src/store/ComponentMetadataStore.ts#L1

So I believe the Analyze package is still active? Thanks in advance.

**Comment by znck** [comment]
The project is in middle of a refactor. You can find analyze package on v0 branch. https://github.com/vuedx/languagetools/tree/v0/packages/analyze
